name: "CF CLI Action"
description: "Deploy and manage Cloud Foundry using the cf cli"

inputs:
  manifest:
    description: The path to your CF application manifest
    required: true
  appdir:
    description: Set this parameter if you want to switch the working dir to push an app
    required: true
  API:
    description: The Cloud Foundry API endpoint
    required: true
  USERNAME:
    description: Your Cloud Foundry authentication username (or email address)
    required: true
  PASSWORD:
    description: Your Cloud Foundry authentication password
    required: true
  ORG:
    description: The name of the Cloud Foundry organization in which to deploy
    required: true
  SPACE:
    description: The name of the Cloud Foundry space in which to deploy
    required: true
  validate:
    description: Whether or not to validate the CF API's TLS certificate
    required: false
    default: true
  debug:
    description: Debug your deploy dir to list all folders
    required: false
    default: false
  command:
    description: "Command to run using CF CLI"
    required: true
    
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
